# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '111.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(544, 410)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 3, 0, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 3, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 5, 1, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 3, 2, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 4, 1, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 4, 0, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 4, 2, 1, 1)
        self.b_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_minus.setObjectName("b_minus")
        self.gridLayout.addWidget(self.b_minus, 3, 3, 1, 1)
        self.b_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_plus.setObjectName("b_plus")
        self.gridLayout.addWidget(self.b_plus, 4, 3, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 2, 2, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 2, 1, 1, 1)
        self.b_multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_multiply.setObjectName("b_multiply")
        self.gridLayout.addWidget(self.b_multiply, 2, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 5, 0, 1, 1)
        self.b_equals = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_equals.setObjectName("b_equals")
        self.gridLayout.addWidget(self.b_equals, 5, 3, 1, 1)
        self.b_divide = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_divide.setObjectName("b_divide")
        self.gridLayout.addWidget(self.b_divide, 1, 3, 1, 1)
        self.monitor = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 0, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "7"))
        self.b4.setText(_translate("Form", "4"))
        self.b5.setText(_translate("Form", "5"))
        self.pushButton_14.setText(_translate("Form", "0"))
        self.b6.setText(_translate("Form", "6"))
        self.b2.setText(_translate("Form", "2"))
        self.b1.setText(_translate("Form", "1"))
        self.b3.setText(_translate("Form", "3"))
        self.b_minus.setText(_translate("Form", "-"))
        self.b_plus.setText(_translate("Form", "+"))
        self.b9.setText(_translate("Form", "9"))
        self.b8.setText(_translate("Form", "8"))
        self.b_multiply.setText(_translate("Form", "*"))
        self.pushButton_13.setText(_translate("Form", "."))
        self.b_equals.setText(_translate("Form", "="))
        self.b_divide.setText(_translate("Form", "/"))
